[env]
TERM = "xterm-256color"

[window]
  dimensions.columns = 200
  dimensions.lines = 60

padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "Menlo"

size = 14
